import type { Snapshot } from "./types.js";
import { assertSnapshotIntegrity } from "../.agents/skills/model-that-fits-my-task/scripts/snapshot-integrity.mjs";

export const MODELS_DB_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://rodion-m.github.io/model-that-fits-my-task/api/v1/schema.json",
  title: "LLM Models Database Snapshot",
  type: "object",
  required: ["schema_version", "generated_at", "content_hash", "workload_profiles", "sources", "benchmarks", "models"],
  properties: {
    schema_version: { const: "1.0" },
    generated_at: { type: "string", format: "date-time" },
    content_hash: { type: "string", pattern: "^[a-f0-9]{64}$", description: "SHA-256 of the hashable snapshot. Health and downloaded snapshot.json share this value." },
    workload_profiles: { type: "array", items: { $ref: "#/$defs/workload_profile" } },
    sources: { type: "array", items: { $ref: "#/$defs/source_status" } },
    benchmarks: { type: "array", items: { $ref: "#/$defs/benchmark_definition" } },
    models: { type: "array", items: { $ref: "#/$defs/model" } },
  },
  $defs: {
    evidence: {
      type: "object",
      required: ["source_id", "url", "fetched_at", "status"],
      properties: {
        source_id: { type: "string" },
        url: { type: "string", format: "uri" },
        fetched_at: { type: "string", format: "date-time" },
        status: { enum: ["observed", "derived", "stale"] },
        fields: { type: "array", items: { type: "string" } },
        derived_from: { type: "array", items: { type: "string" } },
        note: { type: "string" },
      },
      additionalProperties: true,
    },
    price: {
      type: "object",
      required: ["dimension", "unit", "amount_usd_per_unit", "raw", "kind"],
      properties: {
        dimension: { type: "string" },
        unit: { enum: ["token", "million_tokens", "request", "image", "search", "second", "character", "unknown"] },
        amount_usd_per_unit: { type: ["number", "null"], minimum: 0 },
        raw: { type: ["string", "number", "null"] },
        kind: { enum: ["fixed", "variable", "tiered", "scheduled"] },
        tier: { type: "object", required: ["type"], properties: { type: { enum: ["context", "volume"] }, min: { type: "number", minimum: 0 }, max: { type: "number", minimum: 0 } } },
        schedule: { type: "object", properties: { utc_days: { type: "array", items: { type: "string" } }, utc_start: { type: "integer", minimum: 0, maximum: 2359 }, utc_end: { type: "integer", minimum: 0, maximum: 2359 } }, description: "UTC times use HHMM. Start is inclusive, end exclusive; end <= start wraps midnight." },
        override_index: { type: "integer", minimum: 0 },
        cache_write_billing: { enum: ["full_rate", "surcharge"], description: "Whether cache-write pricing replaces ordinary input billing or adds to it. Missing means unknown." },
      },
      additionalProperties: true,
    },
    runtime: {
      type: "object",
      required: ["scope", "evidence"],
      properties: {
        scope: { enum: ["model", "offer"] },
        window: { type: "string" },
        latency_seconds: { type: "object", additionalProperties: { type: "number", minimum: 0 } },
        ttft_seconds: { type: "object", additionalProperties: { type: "number", minimum: 0 } },
        throughput_tokens_per_second: { type: "object", additionalProperties: { type: "number", minimum: 0 } },
        uptime_fraction: { type: "object", additionalProperties: { type: "number", minimum: 0, maximum: 1 } },
        metrics: { type: "object" },
        evidence: { $ref: "#/$defs/evidence" },
      },
      additionalProperties: true,
    },
    api_meta: {
      type: "object",
      description: "Query envelope metadata. scope=available is the default deployable catalog; scope=all is the complete historical catalog.",
      properties: {
        total: { type: "integer", minimum: 0 },
        limit: { type: "integer", minimum: 1 },
        offset: { type: "integer", minimum: 0 },
        has_more: { type: "boolean" },
        updated_at: { type: "string", format: "date-time" },
        schema_version: { type: "string" },
        scope: { enum: ["available", "all"] },
        excluded_count: { type: "integer", minimum: 0 },
        score_direction: { enum: ["higher", "lower"] },
      },
      additionalProperties: true,
    },
    comparison_lane: {
      type: "object",
      description: "Comparable benchmark conditions. A comparison lane includes canonical benchmark_id, evidence.source_id, metric, unit, variant, effort, evaluator, dataset_version, and configuration. Independent sources stay separate when their protocols are unknown. Different lanes must not be ranked together.",
      required: ["benchmark_id", "lane_id"],
      properties: {
        benchmark_id: { type: "string" },
        source_id: { type: ["string", "null"] },
        metric: { type: "string" },
        unit: { type: "string" },
        variant: { type: "string" },
        effort: { type: "string" },
        evaluator: { type: "string" },
        dataset_version: { type: "string" },
        configuration: { type: "object" },
        lane_id: { type: "string", description: "Stable identifier of one comparison lane." },
      },
      additionalProperties: true,
    },
    benchmark_observation: {
      type: "object",
      description: "A source-specific score. Compare scores only inside one comparison lane via GET /api/v1/benchmark-observations.",
      required: ["benchmark_id", "value", "evidence"],
      properties: {
        benchmark_id: { type: "string" },
        source_benchmark_ids: { type: "array", items: { type: "string" }, uniqueItems: true },
        kind: { enum: ["benchmark", "index", "aggregate", "claim"] },
        value: { type: "number" },
        metric: { type: "string" },
        unit: { type: "string" },
        variant: { type: "string" },
        effort: { type: "string" },
        evaluator: { type: "string" },
        dataset_version: { type: "string" },
        sample_count: { type: "integer", minimum: 0 },
        metrics: { type: "object", additionalProperties: { type: ["number", "string", "boolean", "null"] } },
        configuration: { type: "object", additionalProperties: { type: ["number", "string", "boolean", "null"] } },
        evidence: { $ref: "#/$defs/evidence" },
      },
      additionalProperties: true,
    },
    offer: {
      type: "object",
      required: ["id", "provider_id", "provider_model_id", "status", "supported_parameters", "capabilities", "reasoning_efforts", "pricing", "runtime", "measurements", "evidence"],
      properties: {
        id: { type: "string" },
        provider_id: { type: "string" },
        provider_name: { type: "string" },
        provider_model_id: { type: "string" },
        variant: { type: "string" },
        status: { enum: ["active", "absent", "unknown"], description: "Pricing-only catalogs cannot establish route availability." },
        expires_at: { type: "string", description: "Upstream expiration date or timestamp for this offer." },
        quantization: { type: "string" },
        context_tokens: { type: "integer", minimum: 0 },
        max_output_tokens: { type: "integer", minimum: 0 },
        supported_parameters: { type: "array", items: { type: "string" } },
        capabilities: { type: "object", additionalProperties: { type: ["boolean", "null"] } },
        reasoning_efforts: { type: "array", items: { type: "string" } },
        data_policy: { type: "object" },
        pricing: { type: "array", items: { $ref: "#/$defs/price" } },
        runtime: { type: "array", items: { $ref: "#/$defs/runtime" } },
        measurements: { type: "array", items: { $ref: "#/$defs/measurement" } },
        evidence: { type: "array", items: { $ref: "#/$defs/evidence" } },
        source_projections: { type: "object", additionalProperties: { $ref: "#/$defs/offer_projection" }, description: "Original contributions for offers merged from multiple sources. Used to remove one source without retaining its old fields." },
      },
      additionalProperties: true,
    },
    model: {
      type: "object",
      required: ["id", "identity_confidence", "name", "creators", "aliases", "open_weights", "modalities", "capabilities", "reasoning", "offers", "benchmarks", "pricing_observations", "runtime_observations", "measurements", "evidence"],
      properties: {
        id: { type: "string" },
        identity_confidence: { enum: ["exact", "alias", "unresolved"] },
        name: { type: "string" },
        creators: { type: "array", items: { type: "string" } },
        family: { type: "string" },
        aliases: { type: "array", items: { type: "object", required: ["id", "source_id"], properties: { id: { type: "string", minLength: 1 }, source_id: { type: "string", minLength: 1 }, kind: { type: "string" } } } },
        release_date: { type: "string" },
        knowledge_cutoff: { type: "string" },
        open_weights: { type: ["boolean", "null"] },
        license: { type: "string" },
        modalities: { type: "object", required: ["input", "output"], properties: { input: { type: "array", items: { type: "string" } }, output: { type: "array", items: { type: "string" } } } },
        context_tokens: { type: "integer", minimum: 0 },
        max_output_tokens: { type: "integer", minimum: 0 },
        capabilities: { type: "object", additionalProperties: { type: ["boolean", "null"] } },
        reasoning: { type: "array", items: { $ref: "#/$defs/reasoning" } },
        offers: { type: "array", items: { $ref: "#/$defs/offer" } },
        benchmarks: { type: "array", items: { $ref: "#/$defs/benchmark_observation" } },
        pricing_observations: { type: "array", items: { type: "object", required: ["pricing", "evidence"], properties: { pricing: { type: "array", items: { $ref: "#/$defs/price" } }, evidence: { $ref: "#/$defs/evidence" } } } },
        runtime_observations: { type: "array", items: { $ref: "#/$defs/runtime" } },
        measurements: { type: "array", items: { $ref: "#/$defs/measurement" } },
        evidence: { type: "array", items: { $ref: "#/$defs/evidence" } },
        metadata_by_source: { type: "object", additionalProperties: { $ref: "#/$defs/model_metadata" }, description: "Source-specific claims from which scalar metadata is recomputed on replacement." },
      },
      additionalProperties: true,
    },
    offer_projection: { type: "object", allOf: [{ $ref: "#/$defs/offer" }, { not: { required: ["source_projections"] } }] },
    model_metadata: {
      type: "object",
      properties: {
        identity_confidence: { $ref: "#/$defs/model/properties/identity_confidence" },
        name: { type: "string" }, creators: { type: "array", items: { type: "string" } },
        family: { type: "string" }, release_date: { type: "string" }, knowledge_cutoff: { type: "string" },
        open_weights: { type: ["boolean", "null"] }, license: { type: "string" },
        modalities: { $ref: "#/$defs/model/properties/modalities" },
        context_tokens: { type: "integer", minimum: 0 }, max_output_tokens: { type: "integer", minimum: 0 },
        capabilities: { type: "object", additionalProperties: { type: ["boolean", "null"] } },
      },
    },
    reasoning: {
      type: "object", required: ["source_id", "supported", "evidence"],
      properties: { source_id: { type: "string" }, supported: { type: ["boolean", "null"] }, mandatory: { type: "boolean" }, efforts: { type: "array", items: { type: "string" } }, controls: { type: "array", items: { type: "string" } }, evidence: { $ref: "#/$defs/evidence" } },
    },
    measurement: {
      type: "object", required: ["kind", "offer_id", "status", "metrics", "evidence"],
      properties: { kind: { const: "measurement" }, offer_id: { type: "string" }, workload_profile_id: { type: "string" }, reasoning_config: { type: "object" }, status: { enum: ["pass", "fail", "partial", "unknown"] }, sample_count: { type: "integer", minimum: 0 }, metrics: { type: "object", additionalProperties: { type: ["number", "string", "boolean", "null"] } }, evidence: { $ref: "#/$defs/evidence" } },
    },
    source_status: {
      type: "object",
      required: ["source_id", "url", "status", "attempted_at", "record_count", "warning_count"],
      properties: {
        source_id: { type: "string" },
        url: { type: "string", format: "uri" },
        status: { enum: ["ok", "error", "skipped"] },
        attempted_at: { type: "string", format: "date-time" },
        last_success_at: { type: "string", format: "date-time" },
        record_count: { type: "integer", minimum: 0 },
        warning_count: { type: "integer", minimum: 0 },
        error: { type: "string" },
      },
      additionalProperties: true,
    },
    benchmark_definition: {
      type: "object",
      required: ["id", "evidence"],
      properties: { id: { type: "string" }, aliases: { type: "array", items: { type: "string" }, uniqueItems: true }, kind: { enum: ["benchmark", "index", "aggregate", "claim"] }, name: { type: "string" }, category: { type: "string" }, description: { type: "string" }, year: { type: "integer" }, version: { type: "string" }, updated_at: { type: "string" }, dataset_type: { type: "string" }, url: { type: "string" }, evidence: { $ref: "#/$defs/evidence" } },
      additionalProperties: true,
    },
    workload_profile: {
      type: "object",
      required: ["id", "description", "input_tokens", "cached_input_ratio", "output_tokens", "requests_per_task"],
      properties: { id: { type: "string" }, description: { type: "string" }, input_tokens: { type: "integer", minimum: 0 }, cached_input_ratio: { type: "number", minimum: 0, maximum: 1 }, output_tokens: { type: "integer", minimum: 0 }, requests_per_task: { type: "integer", minimum: 1 }, cache_write_tokens: { type: "integer", minimum: 0 }, reasoning_tokens: { type: "integer", minimum: 0 } },
      additionalProperties: true,
    },
  },
} as const;

export function assertSnapshotShape(value: unknown): asserts value is Snapshot {
  assertSnapshotIntegrity(value);
}
